# Site settings
title: Code For Foco
email: people@codeforfoco.org
github_username:  codeforfoco
description: > # this means to ignore newlines until "baseurl:"
  We are programmers, designers, hackers, makers, tinkerers,
  writers and artists and we want to have an impact on the community
  around us.

# Plugins
gems: [jekyll-paginate]

# Conversion
markdown: kramdown
highlighter: rouge
markdown_ext: "md"
encoding: "utf-8"
permalink: pretty

# Serving
port: 8080
baseurl: ""
url: "https://codeforfoco.org"

# Kramdown settings
kramdown:
  input: GFM
